/**
 * Read source output (or fetch live sources), dedupe, score, assign lane,
 * and write INSERT OR IGNORE SQL. Never connects to a database.
 *
 * Usage:
 *   node ingest/upsert.mjs --help
 *   node ingest/upsert.mjs --from-sources --query "product manager" --limit 400
 *   node ingest/upsert.mjs --input ingest/out/jobs.json
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { isCli, parseArgs } from "./cli.mjs";
import { logError, logInfo } from "./logger.mjs";
import { assignLane, dedupeKey, scoreMatch } from "./match.mjs";
import { renderInsertIgnore } from "./sql.mjs";

const ROOT = dirname(fileURLToPath(import.meta.url));
const DEFAULT_OUT_SQL = join(ROOT, "out", "upsert.sql");
const DEFAULT_OUT_JOBS = join(ROOT, "out", "jobs.json");

const SOURCE_LOADERS = {
  greenhouse: () => import("./sources/greenhouse.mjs"),
  lever: () => import("./sources/lever.mjs"),
  ashby: () => import("./sources/ashby.mjs"),
  remoteok: () => import("./sources/remoteok.mjs"),
  himalayas: () => import("./sources/himalayas.mjs"),
  weworkremotely: () => import("./sources/weworkremotely.mjs"),
  jobspresso: () => import("./sources/jobspresso.mjs")
};

/**
 * @param {{ company: string, title: string, url: string, source: string, work_type: string|null, posted: string|null }} job
 * @param {string} updatedAt
 */
export function toJobRow(job, updatedAt) {
  return {
    dedupe_key: dedupeKey(job.company, job.title),
    company: job.company,
    title: job.title,
    url: job.url,
    match_pct: scoreMatch(job),
    source: job.source,
    status: "queued",
    lane: assignLane(job),
    submitted_at: null,
    posted: job.posted,
    work_type: job.work_type,
    updated_at: updatedAt
  };
}

/**
 * First row for a given dedupe_key wins.
 *
 * @param {Array<{ company: string, title: string, url: string, source: string, work_type: string|null, posted: string|null }>} jobs
 * @returns {ReturnType<typeof toJobRow>[]}
 */
export function buildRows(jobs) {
  const updatedAt = new Date().toISOString();
  const seen = new Set();
  const rows = [];
  for (const job of jobs) {
    const row = toJobRow(job, updatedAt);
    if (!row.dedupe_key || row.dedupe_key === "|") continue;
    if (seen.has(row.dedupe_key)) continue;
    seen.add(row.dedupe_key);
    rows.push(row);
  }
  return rows;
}

/**
 * @param {ReturnType<typeof toJobRow>[]} rows
 * @returns {string}
 */
export function renderUpsertSql(rows) {
  const header = `-- generated by ingest/upsert.mjs at ${new Date().toISOString()}
-- INSERT OR IGNORE: existing dedupe_key rows are left untouched
-- this file is not executed against any database by this tool
`;
  return header + rows.map((row) => renderInsertIgnore(row)).join("\n") + "\n";
}

/**
 * Fetch every working source. Indeed is omitted because it has no working feed.
 *
 * @param {{ limit?: number, query?: string }} options
 * @returns {Promise<Array<{ company: string, title: string, url: string, source: string, work_type: string|null, posted: string|null }>>}
 */
export async function fetchAllSources(options) {
  const collected = [];
  const counts = {};
  for (const [id, loader] of Object.entries(SOURCE_LOADERS)) {
    const mod = await loader();
    try {
      const jobs = await mod.fetchJobs(options);
      counts[id] = jobs.length;
      collected.push(...jobs);
    } catch (error) {
      counts[id] = 0;
      logError("source skipped", { id, error: String(error && error.message ? error.message : error) });
    }
  }
  logInfo("source counts", counts);
  return collected;
}

/**
 * @param {{ input?: string, fromSources?: boolean, query?: string, limit?: number, out?: string, jobsOut?: string }} options
 */
export async function runUpsert(options) {
  let jobs;
  if (options.input) {
    const payload = JSON.parse(await readFile(options.input, "utf8"));
    jobs = Array.isArray(payload) ? payload : payload.jobs || [];
  } else {
    jobs = await fetchAllSources({
      query: options.query,
      limit: options.limit
    });
  }
  const rows = buildRows(jobs);
  const sql = renderUpsertSql(rows);
  const sqlPath = options.out || DEFAULT_OUT_SQL;
  const jobsPath = options.jobsOut || DEFAULT_OUT_JOBS;
  await mkdir(dirname(sqlPath), { recursive: true });
  await mkdir(dirname(jobsPath), { recursive: true });
  await writeFile(sqlPath, sql, "utf8");
  await writeFile(jobsPath, JSON.stringify({ generatedAt: new Date().toISOString(), count: rows.length, jobs: rows }, null, 2), "utf8");
  return { sqlPath, jobsPath, count: rows.length };
}

function printHelp() {
  process.stdout.write(`Usage: node ingest/upsert.mjs [options]

Read source postings, dedupe on lower(company)|lower(title), score match_pct,
assign lane, and write ingest/out/upsert.sql. Does not open a database and
does not need credentials.

Options:
  --help                 Show this help
  --from-sources         Fetch live sources (default if --input is omitted)
  --input FILE           JSON file: an array, or { "jobs": [...] }
  --query TEXT           Passed to sources (default: product manager)
  --limit N              Max jobs per source
  --out FILE             SQL output path (default: ingest/out/upsert.sql)
`);
}

if (isCli(import.meta.url)) {
  const argv = process.argv.slice(2);
  if (argv.includes("--help") || argv.includes("-h")) {
    printHelp();
  } else {
    const args = parseArgs(argv);
    const limit = args.limit === undefined ? undefined : Number(args.limit);
    try {
      const result = await runUpsert({
        input: args.input ? String(args.input) : undefined,
        query: args.query === undefined ? "product manager" : String(args.query),
        limit: Number.isFinite(limit) ? limit : undefined,
        out: args.out ? String(args.out) : undefined
      });
      process.stdout.write(`wrote ${result.count} rows to ${result.sqlPath}\n`);
    } catch (error) {
      logError("upsert failed", { error: String(error && error.message ? error.message : error) });
      process.exitCode = 1;
    }
  }
}
